### ISSUE TITLE
Create GS Project Wrangler Job Description

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#10]

**Comment by zee-moz** [comment]
### Project Wrangler Role

Working closely with project leads, the Project Wrangler helps recruit and prepare open projects for a successful Global Sprint. The PW will primarily work with so-called “wild” projects-- projects by led by people who haven’t participated in Mozilla’s Open Leaders Mentoring program, and will likely need some guidance on opening their project for contribution. 

We’ll assign each project to one of the five Internet health issues, determined by content and relevance. Two PWs will be assigned to wrangle the projects grouped under each IH issue.

Tasks for Project Wranglers are as follows:

- **Project Recruitment/Curation:** Help spread the word about the Global Sprint to likely project leads in your communities, with special outreach to those in your IH area. 
- **Project Preparation:** Review and provide feedback on project documentation to ensure projects are newcomer-friendly, welcoming, with clearly defined goals and tasks for the sprint. Point leads to OLTS, OL101 and other resources as needed. 
- **Project Promotion:** Approve contributor-ready for Network Pulse. Work with Sprint Coordinator to get projects mentioned on social media, blogs, etc. 
- **Troubleshooting and General Support:** answer questions about the Sprint process, and provide encouragement and advice to project leads. 

The Project Wrangler role begins in early February, when the Sprint is announced. Depending on project volume, PWs can expect to spend between .05 and 2.5 hours per week on outreach, reviewing documentation, and corresponding with leads. 

The PW role is a great way to start or deepen and strengthen your relationships with IH advocates and creators in your community. You’ll be helping to further projects and grow communities of skilled and enthusiastic contributors around them.

**Comment by chadsansing** [comment]
Looks great. Very clear. A few suggestions:

- Add "(IH)" after first mention of Internet health.
- Note that Global Sprint organizers will provide communications templates to reduce the amount of time Project Wranglers spend recruiting and promoting projects.
- Spell out resources in the Project Preparation section (e.g. "Point leads to working open and open leadership resources like the Open Leadership Training Series (OLTS) or Open Leadership 101 (OL101).").
