### ISSUE TITLE
Project Wrangler Suggestions and Assignments

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#11]
Identify and recruit 10 wranglers for "wild" projects.  See job description: #10 . Let's see if we can get 4 or 5 names for each area, so we're sure to get 2 in the end! Add suggestions in comments...

**"Openness"/Open Innovation**
- Robert? 
- Danielle or Christie?
- Brian Bot
- Kenneth Daily (Sage BN - works w/ Brian)
- Lou Woodley
- Peter Grabitz
- Alex Morley
- Marcos Vital

**Web Literacy**
- Sam D?
- AnMe?
- Robin Champieux
- Edoardo Viola 

**Digital Inclusion**
- Amira?
- Bastian Greshake
- Lou Woodley?
- Samhir Vasdev

**Privacy and Security**
- Chad?
- former or current Open Web Fellow:
  - Jennifer Helsby
  - Etienne Maynier
  - Siddarth (Sid) Rao
  - Becca Ricks
  - Maya Waggoner

**Decentralization**
- Would actually put Danielle here
- Someone from the BBC

**Non-specific suggestions:**

- Daniela
- Sydney
- Samantha Hindle
- Oliver Sauter
- Joe McArthur
- Madeline Bonsma
- David Riordan
- Elisabeth Sylvan
- Rachael Ainsworth
- Arliss

**Comment by chadsansing** [comment]
A few thoughts, questions, & suggestions:

- I am happy to pitch in on Web Literacy or Openness, if needed.
- Would it work to involve Fellows here? Especially for Privacy and Security and Digital Inclusion?
- Meghan for anything.
- Mehan for Decentralization.
- Jen for Digital Inclusion.

Will post more if other ideas occur to me.

**Comment by zee-moz** [comment]
@chadsansing which Jen?

**Comment by chadsansing** [comment]
Apologies - Jen Caltrider.

**Comment by chadsansing** [comment]
The insights/IHR folks might also enjoy or draw some benefit from mentoring GS projects.

**Comment by stephwright** [comment]
I just added a bunch of suggestions from community members

**Comment by abbycabs** [comment]
To help with our KR for engaging OL4 grads, I'd like to take from this list of grads who have signed up to stay in touch / be an expert, but not as a mentor (yet).

List (sharing it in a sheet since I'm not sure they'd all appreciate having their names publicly listed here):
https://docs.google.com/spreadsheets/d/1LdiaTAtUd927AYo9sHI2c7nyfRzUT_ugA8kpXfiIvkg/edit?usp=sharing

**Comment by zee-moz** [comment]
thanks Abby!

**Comment by zee-moz** [comment]
closing this, as we now have a great group of project coaches :)
