### ISSUE TITLE
Schedule Sprint Job Fair 

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#16]
- [x] create job descriptions
- [x] update planning repo
- [x] develop agenda for meeting
- [x] select date -- sometime late week of 2/29
- [x] id and book guests (?)

**Comment by Saallen** [comment]
Going to add some additional tasks
- [x]  Sarah to connect with WPR about support for sites during sprint
- [x] Share open call for Jobs fair on the Project call
- [x] Sarah to email all offices once project call over looking for site hosts

**Comment by zee-moz** [comment]
@Saallen job fair is done, so I'd like to close this issue. where are you with the above tasks?

**Comment by Saallen** [comment]
Done 💯
