### ISSUE TITLE
ZM Tasks Week of 2/5

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#17]
Sprint stuff
- [x] update comms plan
- [x] edit content to add to foundation CMS
- [x] create participant survey 
- [x] draft email re: survey and sprint announcement
- [x] get emails from Ti.To
- [x] send out participant survey
- [x] write better sprint description; use Erika's maker party language
- [x] reach out to partners (Open Innovation Team, Campus Clubs, MDN)
- [ ] plan & schedule job fair
- [x] if needed create Ti.to form 

Other
- [ ] add web lit content to gitHub (2 per day)
- [ ] abby's blog posts-- edits and staging

**Comment by abbycabs** [comment]
Could you also look at #3? I've scheduled time to work on it tomorrow, but I'm blocked on a couple things. Thank you!

**Comment by zee-moz** [comment]
Sure! thanks for the reminder :)
