### ISSUE TITLE
Count Languages in the 2017 Global Sprint

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#18]
@acabunoc to look into this. Thanks abby! 🥇

**Comment by abbycabs** [comment]
I'm 80% sure the language count is 1

Here is the full list of projects from 2017: https://github.com/mozilla/global-sprint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+201

I'll browse through the whole list when I have time (maybe Friday). Others are free to take this on if you have time before I do!

**Comment by abbycabs** [comment]
2 languages!
There were 2 projects in Spanish in 2017.

Closing :)
