### ISSUE TITLE
Convert old GS site to Training site

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#20]
We're converting the old GS site to just host the training pages, as all other info is on the [Foundation site](https://foundation.mozilla.org/opportunity/global-sprint/). 

**We do have a NEW GH pages template for curriculum that matches the foundation site design!** 

It lives here, [in this forkable repo](https://mozilla.github.io/web-lit-core/). 

[Notes on the development of this template are here.](https://github.com/mozilla/foundation.mozilla.org/issues/986) 

@acabunoc I'd like to use this GH pages template for the guide on the GS site. Since we need to preserve the issues from the GH, we can't fork web-lit-core. Can we instead copy over the relevant files and I can just copy-paste in the content? Let me know if this is doable. Again, all pages except for 3 training pages need to go away, as GS landing page is now on the [Foundation site](https://foundation.mozilla.org/opportunity/global-sprint/).  

Maybe this is a fun(?) thing you might do if you're bored on Monday 😉

**Comment by abbycabs** [comment]
Thanks @zee-moz! This isn't *too* much work since it's built off of the template we're using now, but I don't think I'll have time to get it done before Wednesday.

Feel free to edit all the content in the current repo and it shouldn't be a problem to "re-skin" the [stuff here](http://mozilla.github.io/global-sprint/) to match web-lit-core.

**Comment by kristinashu** [comment]
Sorry, I just noticed this ticket and how you had already tried to re-skin the pages.

If it isn't doable to re-skin them then I recommend these few style updates:
- move "Open & the Global Sprint" and "Collaboration Tools for the Sprint" to [main site](https://foundation.mozilla.org/opportunity/global-sprint/tools-working-open/) (this page is in Draft mode so you have to be logged-in to see it)
- update logo to black/white version
- remove text over the banner
- replace banner image with a taller one with branding
- update intro text to link back to the main site

Here is a quick mockup:

![gh-comp](https://user-images.githubusercontent.com/1068783/36571024-a71064ee-17e9-11e8-907f-62ff3a39b707.jpg)

cc @mmmavis who might be able to help with some of these updates (but is also worried about messing up the scripts Abby mentioned).

**Comment by zee-moz** [comment]
@kristinashu thanks for the suggestions. Today I have to work on the Web Lit Core launch (which is also next week) so I can't make these changes.  @acabunoc is this something you can work on today to be ready for launch on Monday?

**Comment by abbycabs** [comment]
If @mmmavis has time today, these changes shouldn't affect the scripts I mentioned before!

Otherwise, I can make some time for this later in the afternoon (or maybe tomorrow) in time for the launch :)

**Comment by kristinashu** [comment]
Just noting that none of this is a blocker for launch. I think both sites are ready and can launch now. Recommended guide dates are improvements, not blockers.

**Comment by abbycabs** [comment]
@kristinashu where can I get the new banner image? Making a few changes now!

**Comment by kristinashu** [comment]
Oooh yay! Here you go: 

[Logo.zip](https://github.com/mozilla/2018-global-sprint-planning/files/1753129/Logo.zip)

![globalsprint-githubpage 2x](https://user-images.githubusercontent.com/1068783/36616601-3a11cb02-1899-11e8-82db-32accfccacba.jpg)

**Comment by abbycabs** [comment]
Made the changes the github site: https://mozilla.github.io/global-sprint/

Haven't moved "Open & the Global Sprint" and "Collaboration Tools for the Sprint" to the main site. I removed them from the navigation of the github site  -- let me know if I should put them back on the  nav!

**Comment by kristinashu** [comment]
w00t w00t! I've published a Tools & Working Open page https://foundation.mozilla.org/opportunity/global-sprint/tools-working-open/

**Comment by abbycabs** [comment]
👏😆🎉 yay! Love these changes

**Comment by zee-moz** [comment]
Thanks everyone for awesome work on the GS sites 💯 ❤️ 🎊
