### ISSUE TITLE
Feedback on the website and Gitpages

### ISSUE THREAD

**Issue by Saallen** [mozilla/2018-global-sprint-planning#21]
The website and gitpages look great. Loving the new banner and the stories. The layout feels very accessible and not too loaded- Well done !!!!!

I noticed some gaps in information I want to share
* On the foundation home page of the home page [https://foundation.mozilla.org/opportunity/global-sprint/] you don't mention anywhere that there are three ways to participate- I can see the sidebar but as a noob, that nuance might be lost on me

* under project lead page on the foundation site the first point
**Every project entered in the sprint should:
    Have a designated project lead to handle the application process- _this reads that I need to find my own- it would be good to clarify that the GS allocates you one_

* In gitpage for site hosts
Under participation guidelines- do we want to say CPG training is mandatory? 
There is one spelling mistake- should is missing the u

cc @zee-moz

**Comment by zee-moz** [comment]
@Saallen thanks! 

- I fixed the 3 ways gap-- take a look now! I've also connected that to the stories, and changed the sidebar language to be more active. 
- It's true that every project has a lead-- and that's the person submitting the project! They do the application form, and connect with participants We do have project wranglers to help, but the lead is primarily responsible, and that's what we're talking about here. I'll tweak the text a teeny bit. 
- I will add the bit about CPG training and fix the spelling mistake!

**Comment by Saallen** [comment]
OOH, I misread that section thinking that every project lead needed a mentor.

Thanks for the updates :)

**Comment by stephwright** [comment]
Oh @zee-moz ... these sites made me so happy!  Seriously.... had that filled up happy feeling in my chest!

Here are my notes:
#### Main site
* Under Lead a Project: could we add a link to Pulse where it's mentioned... preferably a link that already filters for Global Sprint tagged items
* Under Host a Site:
  * make clear in first bullet that it’s over 2 days
  * make clear that all is needed to connect via video conf is a laptop w/ camera and internet access?
  * Do we want to mention that the first X# of sites registered before X date get swag?

#### Training site
FIRST  - <3 how the training site really walks folks through how to participate… Fantastic!  

* Under Collaboration Tools: need actual link to Vidyo instructions
* Participation Guide: 
  * at the bottom there’s a underscore at the beginning of the last sentence of Where and When to Sprint
  * When you click on sub menu items under Participant Guide and go to one of those pages, the sub menu for Participant Guide disappears, meaning you have to go back to the previous page to get the menu back and go to the next sub menu item.
* Finding projects: link to Mozilla Pulse … preferably a link that already selects Global Sprint tagged entries
* Sharing Your Story: link to #mozsprint hash and Gitter chat
* Project Lead Guide: 
  * Leading underscore on sentence at the bottom.
  * Need link to next section on “Project Requirements” at bottom
  * Same issue w/ sub-menu items as in Participation Guide above
* Site host guide: under "Publicizing your site:" there's a sentence that reads “It’s up to spread the word”
* Global Sprint Swag: add a date by which they need to be registered to get swag... did we decide that date already?  It was like April 10 or something, right?

**Comment by zee-moz** [comment]
@stephwright, thanks for the notes! 
**Main Site**
- We don't yet have projects, so we won't have a pulse enabled list for a couple weeks.
- Fixed the sprint days and the video conf reqs, added swag mention w/ registration under next steps

**Training Site**
- vidyo link added
- the dropdown is fixed for the full nav
- no link to pulse yet, as above-- coming soon!
- I'm in the process of getting the global-sprint2017 channel renamed to global-sprint, have to do this via Gitter helpdesk; will add this when that task is complete. #mozsprint added
- added posts from kenya and nepal to increase blog diversity for the share you story examples
- site host typos fixed, added end date for swag.

@kristinashu is working to update the design to better match branding, stay tuned!

**Comment by kristinashu** [comment]
Excellent, I've made a few recommendations for the Training Site in https://github.com/mozilla/2018-global-sprint-planning/issues/20!

**Comment by zee-moz** [comment]
thanks all, we have launched! closing this issue. if you see anything that needs to be corrected on either site, feel free to open a "fixes" issue
