### ISSUE TITLE
Work with Design Team to create print materials

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#22]

**Comment by zee-moz** [comment]
[Design brief is here!](https://docs.google.com/document/d/1wN1jMWm92BqEwtvxHScAlv-cLfMTujIncl4aGphPtm0/edit?usp=sharing). See also #12. @kristinashu can you help? 🙏 

Here are last year's printed fliers... 

Global Sprint Site Announcement ([8.5” x 11” PDF](https://github.com/MozillaFoundation/Design/files/1033127/global-sprint-editable-8p5x11.pdf)) ([11” x 17” PDF](https://github.com/MozillaFoundation/Design/files/1033126/global-sprint-editable-11x17.pdf))
    Participation Guidelines ([8.5” x 11” PDF](https://github.com/MozillaFoundation/Design/files/1033129/participation-guidelines-8p5x11.pdf)) ([11” x 17” PDF](https://github.com/MozillaFoundation/Design/files/1033128/participation-guildelines-11x17.pdf))
    What is Mozilla? ([8.5” x 11” PDF](https://github.com/MozillaFoundation/Design/files/1033130/what-is-mozilla-8p5x11.pdf)) ([11” x 17” PDF](https://github.com/MozillaFoundation/Design/files/1033131/what-is-mozilla-11x17.pdf))

Postcard design will be new.

**Comment by xmatthewx** [comment]
hi @zee-moz - do you need updates to the signage content?

**Comment by zee-moz** [comment]
only changes are to the dates of the Sprint, and the shortlink to the site:
This year the sprint is May 10 & 11, 2018.
The main site shortlink is now: mzl.la/global-sprint

I think the What is Mozilla is Okay for another year 😸 

I think the CPG text is fine, but would want to hear from @chadsansing... thoughts?

**Comment by chadsansing** [comment]
I was looking at these today for use at the IoT Escape Room event this week and thought they were great. We may have some alt text later in the year or 2019 for the CPG flier, but it's a great TL;DR - wouldn't worry about changing it for the Sprint, especially since we plan to work with D&I to get the leads and hosts some additional training.

**Comment by sabrinang** [comment]
@zee-moz Can you clarify some specifications for the postcard:
- Do you have preferred dimensions? a typical default is 4”x6”
- Are you doing double-sided printing or single side? Good to know for designing the write-in area or I can leave the back empty for write in area if we are single side printing 
- Other than event name/date, does this general announcement postcard have any other copy or content required on it? 

On the brief you wrote “The signage is basic welcome stuff, and the CPG” can you unpack what signage you are requesting (I’m confusing if you are referring to revising the three fliers above or requesting something new entirely)

**Comment by zee-moz** [comment]
hi @sabrinang when i said: “The signage is basic welcome stuff, and the CPG”  I meant that we'll use the content that was in last year's signs, and only update the graphics and dates, and shortlink

**Comment by zee-moz** [comment]
Answers to postcard questions @sabrinang: 
* Default size is fine. 
* Text adapted from the signage:
"Join our world-wide collaboration party for the open Web!
On May 10-11, scientists, educators, artists, engineers, students and others will gather in person and online to work on projects that make the internet a better place. We'll collaborate on everything from games to promote online privacy to apps for sharing research data to coding languages for artists. All skill levels welcome! Join us locally at ______________________
Host contact: __________________________"
* I am OK with 2 sided printing; we've done it in the past.

**Comment by sabrinang** [comment]
@zee-moz I iterated on the postcard and updated dates, link, colours. You can leave feedback on: https://redpen.io/p/nw5e8492a7d0c71b13

I included a version of the post card back that contains less text as an option for feedback too.

**Comment by zee-moz** [comment]
Hey, I'm off today but will look on Monday! Thanks so much for your help on
this :)
Cheers,
Zannah

**Comment by zee-moz** [comment]
@sabrinang these look great. redpen isn't letting me log in to comment, so feedback is here: 

 I would add a teeny bit more text to the front of the post card, as most people  probably don't know what the Global Sprint is. If you can fit something like "worldwide collaboration party for the open web" would encourage them to flip the card over to learn more. 

Then, on the back of the card, maybe just saying : 
On May 10-11, join scientists, educators, artists, engineers, students and others to work on projects that make the internet a better place-- from board games to promote online privacy to apps for sharing research data to coding languages for artists. All skill levels welcome!

@stephwright want to weigh in?

**Comment by zee-moz** [comment]
@sabrinang @kristinashu for the postcards, we expect to print them and mail them to the sites as part of the swag packs. For those host who don't have good access to printing tech, this will make advertising their sites much easier. 

Do you have suggestions for print companies to use? We'd like to print and ship directly to our swag distribution team (in US, Canada, UK, Europe, Africa) who will send packets to nearby sites. 

@edrushka if you have experience with printing for Mozfest, please weigh in as well 😸

**Comment by stephwright** [comment]
+1 on @zee-moz recs above.  Other than that, love it!

**Comment by edrushka** [comment]
@zee-moz sorry for the slow reply - it took me a bit to dig this up. Robert F. and I used [Zazzle](https://www.zazzle.com/create_your_own_horizontal_postcard-239848217395282525) to create some Internet Health postcards for the SF All Hands. It was cheap and we were pleased with how well they turned out.

**Comment by zee-moz** [comment]
@sabrinang  let me know when you've updated the cards and they are good to print! we'll want to order them 3/26 or 3/27 at the latest 😸

**Comment by sabrinang** [comment]
@zee-moz Revised back and front and let me know if you have anymore feedback for it: https://redpen.io/p/nw5e8492a7d0c71b13 

I exported the postcards (with 0.125" bleed) and posters as .pdf files here: https://drive.google.com/open?id=1-iK24Mgm1UkfcdhGgQj5yZutwZEjh3SY

**Comment by sabrinang** [comment]
@zee-moz Did these assets work for you? I have not heard back so I am unsure if you sent to print earlier this week

**Comment by zee-moz** [comment]
@sabrinang hi! sorry for the delay, super busy with site registrations this week. these look good, except there is a small typo on the back card text-- a "v" before the word "better". 

Also it might help to add the words: **"your local sprint location"** and **"your local Sprint host:"** or maybe **"your local sprint details:"** on a line where the blank space starts-- that way people know what to write in there.

otherwise,  think we're good to go! @stephwright want to take one last look before we print?

**Comment by stephwright** [comment]
Took a look... and they are fantastic!  Love your suggestions, @zee-moz ... I'd say incorporate those and we're good to go.

**Comment by sabrinang** [comment]
@zee-moz I have updated the postcard text by the blank lines ("your local sprint location" and "your local sprint host") and fixed the typo. The pdf is updated in the folder: https://drive.google.com/open?id=1-iK24Mgm1UkfcdhGgQj5yZutwZEjh3SY

**Comment by zee-moz** [comment]
great! @stephwright, print away!
