### ISSUE TITLE
Add FAQs and Site Host Checklist to Training Site

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#24]
combine FAQs or keep separate?
any updates to site checklist?

**Comment by Deborah-Digges** [comment]
Is there any help needed in this area? I'd be happy to volunteer for any site related changes :-)

**Comment by zee-moz** [comment]
Hi @Deborah-Digges thanks for the offer! That's fantastic. 

The Site Host Checklist for this year is here: https://mozilla.github.io/global-sprint/site-hosts-guide/checklist/ The checklist starts with tasks 2 weeks before the sprint, but we could be offering more in the way of coaching on getting the word out starting 4 weeks before (that would be next week!).  I know you're an experienced Sprinter-- if you'd like to review and make some suggestions, that would be awesome! 😄 

We also had FAQs last year-- these are not yet on the  2018 site, but visible in last year's archive: https://github.com/mozilla/global-sprint/blob/2017/_articles/site-hosts.md

When we re-wrote the Guide for this year, we may have covered many of these issues-- so for the FAQs it's a matter of looking and seeing what's redundant, and what kinds of questions we might want to add. 

Let me know if you'd like to jump in on either of these tasks, and if you have any questions. In both cases you could add suggestions  as a comment below, to start. 

Thanks! 💯

**Comment by Deborah-Digges** [comment]
Hi @zee-moz !!

Thanks so much for the warm welcome and detailed follow up :) Really excited to join this effort. I've participated remotely before and it was an absolutely wonderful experience.

I just went through the Site Host Checklist and thought of a few things we could add in:

1. Add the link for ti.to: https://ti.to/home
2. For tweets, have we decided on the hashtag yet? If so, we could include that as well in the instructions for sharing work on social media 
3. Would it be a good idea to ask site hosts to bring in a few mentors who are familiar with open source if there are beginners who need a little extra help getting started?
4. Could we add a link to a sample photo release form like [this](https://formswift.com/photo-release-form) for example?

**Comment by Deborah-Digges** [comment]
A couple of things we could add in from the FAQs to the current site hosting Guidelines:

1. A link to current sites would definitely be useful to allow people to see if there are other sites also being hosted in the same location
2. The privacy policy regarding any data provided by the site host may be added in
3. This point would be a great addition as it isn't currently mentioned in the Site host check list: `We'll have daily video conference check-ins for sites in the same time zone so you can meet other participants and hear about project work underway.`

What do you think? 😃

**Comment by zee-moz** [comment]
@Deborah-Digges thanks so much for this! I was traveling last week, so I'm sorry for the slow reply. 
These are all great suggestions! I'll be making edits today and tomorrow. 

Thanks so much for your help 🌟 💯
