### ISSUE TITLE
Look at 2017 data to find most popular projects and contribution types

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#25]
What were the most popular projects in last years sprint? what kinds of contributions were people making? code, content, comments, etc. @acabunoc can you help? 🙏  request from Lucy 😸

**Comment by abbycabs** [comment]
flagging @LucyeoH

You can see an overview of the contributions in the ["MozSprint by the (GitHub) Numbers"](https://medium.com/read-write-participate/mozsprint-by-the-github-numbers-49d518551725) post from last year.


## What were the most popular projects in last years sprint? 
This graph plots the # of github events vs # of contributors: 
[<img width="929" alt="screen shot 2018-03-06 at 3 08 22 pm" src="https://user-images.githubusercontent.com/617994/37055658-3e40dfb4-2150-11e8-973a-c015f115dc86.png">](https://docs.google.com/spreadsheets/d/11WYGSdh9_CVu754ZcHwpAHrWvKNQ7hu7uJq15dpa2Dc/pubchart?oid=40978451&format=interactive)
Zooming in the top 10 projects are:
* [openSNP/snpr](https://github.com/openSNP/snpr)
* [data-lessons/library-openrefine](https://github.com/data-lessons/library-openrefine)
* [phageParser/phageParser](https://github.com/phageParser/phageParser)
* [dib-lab/osf-cli](https://github.com/dib-lab/osf-cli)
* [the-method/podcast](https://github.com/the-method/podcast)
* [data-lessons/library-webscraping](https://github.com/data-lessons/library-webscraping)
* [mozilla-neutrino/neutrino-dev](https://github.com/mozilla-neutrino/neutrino-dev)
* [mozilla/global-sprint](https://github.com/mozilla/global-sprint)
* [nteract/hydrogen](https://github.com/nteract/hydrogen)
* [cliqz-oss/privacy-bot](https://github.com/cliqz-oss/privacy-bot)


## what kinds of contributions were people making?
﻿
![chart](https://user-images.githubusercontent.com/617994/37055912-e60f7f70-2150-11e8-9a63-a130aa8d5bd6.png)
interactive version: https://docs.google.com/spreadsheets/d/e/2PACX-1vRLRhA5jQ6kBO9HTmx3slTdVbGQLbyHB4HPS1_yuJjkTDWNygw2z08pzha6fNdhZha61Oey3_NTr0d9/pubchart?oid=500876013&format=interactive

302 pull requests closed (7% of all activity)
320 pull requests opened (7% of all activity)
2223 comments & issues (51% of all activity)
824 commits pushed (19% of all activity)

**Comment by zee-moz** [comment]
Thanks Abby! :)
