### ISSUE TITLE
Open Registration

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#27]
To open registration, we need to add the Global Sprint site map to the Foundation site. Embed code is on [this Staging page](https://foundation.mofostaging.net/opportunity/map-embed/) per @xmatthewx 

[Registered sites](https://docs.google.com/spreadsheets/d/1-JyApZ-AyBd9XX9vRoqX-zP_XHM-nRa-onWqhgtWcRU/edit#gid=1874859390) are here. I'm updating to add Ti.to links on an ongoing basis. @auremoser let me know what additional data you'll need to create the database and generate the map (country codes?)

@kristinashu any edits to the Registration page (currently hidden) to accommodate the map? 

It would be FANTASTIC if we could get the Registration page up by Thursday of this week!

cc @acabunoc 

Thanks 😃 !

**Comment by zee-moz** [comment]
I had a great meeting with @auremoser about the site map; she'll help with the database and layout. Let's try to get this page up by Friday, so participants can find sites and we can get those registrations pouring in :)

@acabunoc last year we had a special script in the site spreadsheet that was exporting data to use in the map. This script option isn't in the new form-- abby should we add it? Also, I notice in the new form we don't have the country code column. I remember this being important; should we add that column to the form or to the spreadsheet (and if we do, will it mess anything up?) 

@auremoser if you find time to make a comp of the map tomorrow, would you share it here and tag @kristinashu? we discussed colors and design, and she's give you the best feedback. 

Thanks everyone 😺

**Comment by abbycabs** [comment]
the script generated markdown for last year's site. Not for the map, but for the list of sites below. I don't know what's needed for this year! 
Can you paste html into the cms? do you have an html template for each site?

If yes to both, I can put together another custom script. A few hours work. Will trade work.

**Comment by zee-moz** [comment]
@kristinashu @xmatthewx can you answer abby's questions about the CMS and HTML? 
thanks! cc: @auremoser

**Comment by kristinashu** [comment]
Sorry but I'm not too sure what the question is? If you login to the CMS at https://foundation.mozilla.org/admin/ there is a code editor. It's pretty limited but will that do? 

<img width="1432" alt="screen shot 2018-03-21 at 1 15 45 pm" src="https://user-images.githubusercontent.com/1068783/37735064-2bd06c26-2d0a-11e8-8d75-0338d5e4990e.png">

**Comment by abbycabs** [comment]
Okay, I can have the script generate the html inside the .map-sites div listing all the countries.

But @zee-moz -- you're going to have to copy paste it into the code editor at the right place. Also, I'm not sure I'll have time to work on this till next week -- is that okay?

Alternatively, you can use the WSIWYG editor to manually add links to all the tito sites as they come in

**Comment by xmatthewx** [comment]
@acabunoc - the cms will strip out scripts. I tested the map embed on staging, and it works. Your list of links will likely need to be added manually. Hopefully this isn't extra work, just a different workflow.

**Comment by abbycabs** [comment]
Thanks @xmatthewx!

@zee-moz hope you're okay manually adding links to the page

**Comment by zee-moz** [comment]
@xmatthewx @acabunoc it's def not ideal, but I don't think I have another option, right? 🙃 

@kristinashu if you have any design tweaks to make to the registration page (we expect to have maybe 80-100 sites or so, to give you a sense of volume), please make them now! cc: @auremoser 

https://foundation.mozilla.org/opportunity/global-sprint/register/

**Comment by kristinashu** [comment]
I don't have any design updates for the site. @auremoser I recommend making the map itself as neutral as possible (maybe even grey scale) and then making the locations pins the bright blue #071cd1 or pink #ec417a so they stand out nicely.

**Comment by abbycabs** [comment]
@zee-moz do you have a tito link for virtual participants? The current page links to the 2017 virtual participation.

**Comment by zee-moz** [comment]
@acabunoc here's the virtual link https://ti.to/Mozilla/global-sprint-virtual18

do you need me to add a country code column in the Site Spreadsheet?

**Comment by abbycabs** [comment]
I think the country code was for the map, not for the list. I'd check with @auremoser

**Comment by abbycabs** [comment]
oh wait! it was for the icons! We don't have them on the foundation site, so no need

**Comment by zee-moz** [comment]
great! less work on that step 😸

**Comment by abbycabs** [comment]
Preview page is setup with existing sites: https://foundation.mozilla.org/opportunity/global-sprint/register/

To update the site list:
1. In the site registration form responses, click on '**Global Sprint**' > '**Expert data for registration page**'
<img width="791" alt="screen shot 2018-03-23 at 4 10 34 pm" src="https://user-images.githubusercontent.com/617994/37851303-c527c5ee-2eb4-11e8-992e-00a28777e455.png">

2. Copy the content in the pop-up:
<img width="602" alt="screen shot 2018-03-23 at 4 11 48 pm" src="https://user-images.githubusercontent.com/617994/37851354-ed24662e-2eb4-11e8-8927-b39020c6dc34.png">

3. Paste it into the code edit view on the cms
https://foundation.mozilla.org/admin/landingpage/landingpage/32/change/
<img width="672" alt="screen shot 2018-03-23 at 4 12 41 pm" src="https://user-images.githubusercontent.com/617994/37851384-091f3c50-2eb5-11e8-819d-84bbad29a56a.png">

**Comment by auremoser** [comment]
Hey Folks!

I put together the following map based on @zee-moz 's latest [sites spreadsheet](https://docs.google.com/spreadsheets/d/1-JyApZ-AyBd9XX9vRoqX-zP_XHM-nRa-onWqhgtWcRU/edit#gid=1874859390). The [map](https://auremoser.carto.com/builder/4096455f-09f9-4176-bf24-c210edb7e239/embed) currently features 30 sites (up to Goa in the sheet).

As last year, we have the site point data as dots, and an underlayer featuring different timezones. I read above that @kristinashu wanted a minimalistic map, so let me know if you'd like me to remove the timezones. 

* **basemap** - I used the `#071cd1` bright blue for the oceans, and while for the countries with borders in a lighter blue `#7a88fb`. 
* **dots** - I used the `#071cd1` bright blue for the fill, and pink `#ec417a` for the border (to make overlapping dots discernable). 
* **tooltip** - I used pink `#ec417a` for the header with the site-name, and included details on the timezone, city, country, twitter of host, and ti.to site. @zee-moz let me know if there's more info you'd like there.

## Screenshots
Map ([link here](https://auremoser.carto.com/builder/4096455f-09f9-4176-bf24-c210edb7e239/embed)):
![screen shot 2018-03-26 at 1 58 35 pm](https://user-images.githubusercontent.com/1559703/37905337-cf35650e-30fe-11e8-9fb0-5d7675c6f65b.png)
Tooltip:
![screen shot 2018-03-26 at 1 59 06 pm](https://user-images.githubusercontent.com/1559703/37905348-d8979ab8-30fe-11e8-8be2-b049701514d9.png)

## Embed Code
```
<iframe width="100%" height="520" frameborder="0" src="https://auremoser.carto.com/builder/4096455f-09f9-4176-bf24-c210edb7e239/embed" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>
```

## Map URL
```
https://auremoser.carto.com/builder/4096455f-09f9-4176-bf24-c210edb7e239/embed
```

Let me know if you have any requests or edits. Thanks!

**Comment by kristinashu** [comment]
Thanks @auremoser! I've embedded this on the site https://foundation.mozilla.org/opportunity/global-sprint/register/ (need to be logged in to see it).

Maybe the time zones could be a lighter blue so it's a little more subtle.

* **basemap** - Could use a much lighter blue like `#b4baf1`for the oceans, and even lighter blue `#cdd2f6` for the borders. 
* **dots** - Reverse the dot colors. So `#ec417a` pink for the fill, and dark blue `#071cd1` for the border.
* **tooltip** - Nice!

**Comment by auremoser** [comment]
Done @kristinashu !

* [x] basemap - Could use a much lighter blue like #b4baf1for the oceans, and even lighter blue #cdd2f6 for the borders.
* [x] dots - Reverse the dot colors. So #ec417a pink for the fill, and dark blue #071cd1 for the border.

## Screenshot
![screen shot 2018-03-27 at 10 27 54 am](https://user-images.githubusercontent.com/1559703/37955715-a8f98c3e-31a9-11e8-8289-4a44c9635acc.png)

A little ghosty but more subtle. Let me know if you want to me to change the size of the dots or the stroke line width around them. We can play a bit with opacity too. Otherwise, should be good to go!

**Comment by kristinashu** [comment]
So sorry @auremoser you were totally right about the timezones! Do you mind switching it back to the dark blues you had originally done? But keep the dots are is, I think they stand out better now.

And the page is now live! https://foundation.mozilla.org/opportunity/global-sprint/register/

**Comment by auremoser** [comment]
Done, back to dark base, same dots!

Here's the [map](https://auremoser.carto.com/builder/4096455f-09f9-4176-bf24-c210edb7e239/embed):
![screen shot 2018-03-29 at 11 11 00 am](https://user-images.githubusercontent.com/1559703/38080511-fac6a094-3341-11e8-886f-154f5bef26c6.png)


Whoot!

**Comment by kristinashu** [comment]
Perfect, thanks @auremoser!

@zee-moz both [Register page](https://foundation.mozilla.org/opportunity/global-sprint/register/) and [Projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/) are live! I've also updated all the Pre-register links and text to the actual Register page. Please just double check them and let me know if you need anything else!

**Comment by zee-moz** [comment]
thanks everyone! 💯
