### ISSUE TITLE
Allowing Spanish Project Submissions

### ISSUE THREAD

**Issue by abbycabs** [mozilla/2018-global-sprint-planning#31]
Things to localize to Spanish:
- [x] Project submission form - https://docs.google.com/forms/d/1CnoCh_NMez4n7i3NV-J9ZlR4t8wCKxwdQoplS77u0Yw/edit (edit this version directly!)
- [x] Content in this Google Doc - https://docs.google.com/document/d/1-j5A5o4wFNyzjs0mpLpmWytHF3Qsmv7L9LbSOVXr708/edit# Includes:
  - [x] email confirmation
  - [x] github issue template
- [x] mozsprint-repo-template - https://github.com/acabunoc/mozsprint-repo-template

Thanks @mattdark & @lasr21 for your help here!

**Comment by abbycabs** [comment]
For anyone reading, if you're interested in localizing + [coaching projects](https://github.com/mozilla/2018-global-sprint-planning/blob/master/project-coach.md) in another language, let me know!

**Comment by lasr21** [comment]
Hello @acabunoc finally, @mattdark  and I just finish the docs, we notice that the template wasn't in Spanish so we translate it -> https://github.com/acabunoc/mozsprint-repo-template/pull/7

**Comment by abbycabs** [comment]
that's amazing! Thank you so much @mattdark & @lasr21 -- I'll have a look later today and ping you before everything goes live.

**Comment by abbycabs** [comment]
And it's live! Spanish projects can submit here: https://goo.gl/forms/BB7ifmO2FCc29EGF3

**Comment by abbycabs** [comment]
I'd love to send a few tweets to promote this. If you have anything I can tweet in spanish let me know!
