### ISSUE TITLE
Create temporary Project page on Foundation Site

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#33]
we need projects to appear on the foundation site, to help drive registration
per @xmatthewx we're some time away from pulling in projects dynamically from Pulse. 

@kristinashu, using the "three images" structure we used for the Sprint stories, could you set up a project page grid of six project images that link to entries on Pulse, and a big button that says: click here to browse featured projects on Pulse?  We'll also include a link to all projects on GitHub. 

For this temporary page, here are the six we'd like to feature. All have submitted to Pulse:

- Neutrino
- Web + Messaging
- OpenSNP
- gPanel
-WikiPathways

@acabunoc these projects are still in moderation. do we have to wait for coaches to do documentation review? or are they strong projects that have know good documentation so we can approve now to get the page going?

**Comment by kristinashu** [comment]
Gavin should have the embed done and reviewed by the end of day Monday. So if you are definitely announcing Monday then I can do a temporary grid of projects

**Comment by zee-moz** [comment]
I think it's OK to wait until end of day Monday! No need for a temporary
page. Thanks :)

**Comment by kristinashu** [comment]
Ok excellent!
