### ISSUE TITLE
create 2018 post-sprint survey

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#34]
last year's survey can be found here: #4 
please comment with edits and new questions  cc: @chadsansing

**Comment by chadsansing** [comment]
Suggestion:

- How did you find your way to the Global Sprint? [Drop-down: Open Leaders Program, Open Leadership 101, Open Leadership Training Series, Past Global Sprint(s), Open Leadership Framework, MozFest, Other (please explain)]

**Comment by chadsansing** [comment]
Working on this with Kristina.
