### ISSUE TITLE
Add a Content License to the GS repo

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#38]
Abigail  P. says: 

"The Github Global Sprint repo only has a software license. I would include a content license as well, especially since this is the advice Mozilla gives to Project Leaders."

Abby, can you add? Thanks!

**Comment by abbycabs** [comment]
already in the footer!
<img width="407" alt="screen shot 2018-04-27 at 7 31 36 pm" src="https://user-images.githubusercontent.com/617994/39388909-a3a43a98-4a51-11e8-8885-fb2ef311676b.png">
