### ISSUE TITLE
Create Survey for 2017 Participants

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#4]
Survey should be sent to all leads, hosts, and participants
Draft list of questions: 

- Did you attend Y/N
- At the 2017 sprint, I (check all that apply) contributed to my open project, contributed to someone else's open project, networked/met people, learned a new skill, started a project, did something positive for the internet, learned something new about working open, other
- Role (check box)
- Rate your experience (1- poor experience  to 5- great experience)
- Would sprint again Y/N
- Your field/background
- Areas of interest (from IH list)
- Finish this sentence (optional) At the 2018 Sprint, I would like to... 
- Any thing else you'd like to tell us? (optional)

**Comment by zee-moz** [comment]
@chadsansing @acabunoc @stephwright @saallen feedback welcome on survey questions-- should take just a couple minutes!

**Comment by Saallen** [comment]
Slight tweet to your 2nd Q
* At the 2017 sprint, I (check all that apply) 
contributed to my open project, contributed to someone else's open project, started a *NEW* project
learned a new skill, network and met some new ppl, did something positive for the internet, learned something new about working open, other

I would also ask 
* did you sprint from a site? If so which one
* are you still contributing to that project? ( under question two)
* if you wrote a blog please share

**Comment by chadsansing** [comment]
Maybe an item rating the level of support received from wranglers and/or staff?

Maybe also a Y/N/Y& item asking if the respondent joined another project after the sprint, participated in another Mozilla program or event, or both?

**Comment by stephwright** [comment]
Can I ask what we're looking for w/ the option in Q2 for "did something positive for the internet"... I'm not entirely clear what that means or would be... and what do we do with that info if we collect it?

I would recommend that every question we ask has some action that we can take tied to it.  For instance, for Q6, we can identify areas of expertise we may need to target for the Sprint based off those responses.  For the "rate your experience" and "would you sprint again" questions, we really need to know the why behind those to be useful, so maybe "tell us what you liked about the sprint" & "what would you like to see change for the next Sprint"

I would also try to make this no more than 10 questions with only 2-3 of them open-ended questions and the rest easy tic box type things.  May mean needing to prioritize questions to ask for impact and action-ability (I made that last word up, so hopefully it makes sense).

**Comment by zee-moz** [comment]
@stephwright with that question, I'm trying to determine if participants are connecting their work at the Sprint with Mozilla's broader mission to promote Internet Health, as evidenced by the 5 areas. If no-one checks that box, then we're not doing a good job of linking this work with IH and need to find ways to do that better. I could say "did something to promote a healthy internet". If this question seems out of left field, then maybe WE haven't made that connection well enough!

I totally get you on needing follow-ups for questions. I'd like to have both. Being able to say 80% or 10% of people had a good sprint experience, and knowing that 75% of people "would sprint again" is very important-- to me as organizer. If only 15% of people would Sprint again, we have a problem!

I agree-- only 10 questions.  I'll work to edit.

**Comment by zee-moz** [comment]
[Survey is here](https://docs.google.com/forms/d/1yd_s6MR8ZRDPWghq1p0Hq6BUr50pCL7qo2UHVo_DgbQ/edit)

Text of survey email:

_Hello from Mozilla_

_I'm writing because last Spring you registered to participate in the 2017 Mozilla Global Sprint.
We've set the dates for this year's event-- May 10 & 11th 2018-- and we're busy planning an awesome Global Sprint for 2018. Part of this process is hearing your opinions about the 2017 Sprint, so we can make the event more productive, fun, and worthwhile for you._

_Please take a moment to fill out this very quick survey (It should take 3 minutes or less). And stay tuned for updates on the 2018 Sprint._

_Thanks for your help!_

**Comment by zee-moz** [comment]
Done!
