### ISSUE TITLE
Schedule Hosts for Demo Calls

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#41]
@acabunoc do you want to suggest OL cohort members? any specific suggestions?

**Comment by abbycabs** [comment]
This is a pretty late ask - so I'd start with the hosts. And see if the hosts would recommend anyone in their cohorts.

@chartgerink
@macruzbar
@Monsauce
@priyankanag
@rainsworth
@schae234
@syswsi
@yochannah

Can you link the schedule so people know when the calls are?

**Comment by zee-moz** [comment]
yes! https://public.etherpad-mozilla.org/p/2018globalsprint

**Comment by Monsauce** [comment]
@SamanthaHindle or @chrisbresky do either of you want a slot during the North America call?

**Comment by yochannah** [comment]
I'll be at the Mozilla London office for the sprint, and can volunteer to host one or both of the UK morning time ones (   Europe / Africa / Asia 10:00 UTC     11AM BST / 12AM CEST / 3:30PM IST / 6AM EDT) so long as it's ok with @bunnybooboo and co...

**Comment by chrisbresky** [comment]
What does that entail?

**Comment by macruzbar-zz** [comment]
Would this be like hosting an OL cohort meeting? Would we need to be available all day? I have some meetings here and there, but I could get the call started at 10 am

**Comment by zee-moz** [comment]
@chrisbresky @macruzbar great questions!

you don't have to be available all day-- it's just for the Sprint demo call, so about an hour or so of presentations. similar to the OL cohort calls-- you are not presenting anything, just welcoming, facilitating the speakers, making sure the call goes smoothly. Only one per person, in your appropriate time zone. 

agenda is in this pad: 
https://public.etherpad-mozilla.org/p/2018globalsprint

abby put together some tips for emcee'ing calls (this is an old science community doc, but the basic info is the same) 
https://github.com/mozillascience/learning/blob/master/emcee-tips.md

**Comment by zee-moz** [comment]
@yochannah @bunnybooboo I have you on for 11am BST 
David on Thurs
Yo on Friday

Thanks so much 💯 😸

**Comment by zee-moz** [comment]
@macruzbar would you be able to do:    North America / South America 17:00 UTC  10AM PDT / 1PM EDT /  on either Thurs or Friday? Again, just host/emcee the call, about 1 hour or so

**Comment by macruzbar-zz** [comment]
Yes, I can host for an hour. Would this be starting at 10 am PST?
I saw the agenda on the etherpad, but there was no specific info about demo call start and end times.

**Comment by zee-moz** [comment]
the start times for the calls should be above the sign-up blocks.
around lines 46 and 89-- 10 pm PT
I don't think they'll go for more than an hour-- if they run longer than that and you can't stay on, we have a back-up person who can take over.  It's so awesome  you can help out!  Let us know Thurs or Friday!

**Comment by chartgerink** [comment]
Sorry, I will not be able to host this! I'm doing some sprinting intermittently and taking some mental  health "sprints" too.

**Comment by macruzbar-zz** [comment]
Just signed up to host tomorrow, too!

**Comment by zee-moz** [comment]
@macruzbar  thanks so much !  ✨ 👏 ✨
